
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author zoop
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_border = new javax.swing.JPanel();
        label_loginrheader = new javax.swing.JLabel();
        panel_bg = new javax.swing.JPanel();
        passfield_pass = new javax.swing.JPasswordField();
        button_cancel = new javax.swing.JButton();
        label_pass = new javax.swing.JLabel();
        label_acc = new javax.swing.JLabel();
        label_login = new javax.swing.JLabel();
        button_login = new javax.swing.JButton();
        textfield_uname = new javax.swing.JTextField();
        label_uname = new javax.swing.JLabel();
        label_close = new javax.swing.JLabel();
        label_minimize = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panel_border.setBackground(new java.awt.Color(161, 145, 88));

        label_loginrheader.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        label_loginrheader.setForeground(new java.awt.Color(240, 240, 240));
        label_loginrheader.setText("LOGIN");

        panel_bg.setBackground(new java.awt.Color(40, 57, 113));

        passfield_pass.setBackground(new java.awt.Color(250, 250, 250));

        button_cancel.setBackground(new java.awt.Color(175, 175, 175));
        button_cancel.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        button_cancel.setText("Cancel");
        button_cancel.setToolTipText("");
        button_cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_cancelMouseClicked(evt);
            }
        });
        button_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cancelActionPerformed(evt);
            }
        });

        label_pass.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label_pass.setForeground(new java.awt.Color(250, 250, 250));
        label_pass.setText("Password");

        label_acc.setForeground(new java.awt.Color(250, 250, 250));
        label_acc.setText("Don't have an account?");

        label_login.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        label_login.setForeground(new java.awt.Color(250, 250, 250));
        label_login.setText("Click here to register.");
        label_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_loginMouseClicked(evt);
            }
        });

        button_login.setBackground(new java.awt.Color(161, 145, 88));
        button_login.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        button_login.setForeground(new java.awt.Color(250, 250, 250));
        button_login.setText("Login");
        button_login.setToolTipText("");
        button_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_loginMouseClicked(evt);
            }
        });
        button_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_loginActionPerformed(evt);
            }
        });

        textfield_uname.setBackground(new java.awt.Color(250, 250, 250));
        textfield_uname.setCaretColor(new java.awt.Color(40, 57, 113));
        textfield_uname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield_unameActionPerformed(evt);
            }
        });

        label_uname.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        label_uname.setForeground(new java.awt.Color(250, 250, 250));
        label_uname.setText("Username");

        javax.swing.GroupLayout panel_bgLayout = new javax.swing.GroupLayout(panel_bg);
        panel_bg.setLayout(panel_bgLayout);
        panel_bgLayout.setHorizontalGroup(
            panel_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_bgLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(panel_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_bgLayout.createSequentialGroup()
                        .addComponent(label_uname, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textfield_uname, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_bgLayout.createSequentialGroup()
                        .addComponent(label_acc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_login)
                        .addGap(8, 8, 8))
                    .addGroup(panel_bgLayout.createSequentialGroup()
                        .addComponent(label_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(panel_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panel_bgLayout.createSequentialGroup()
                                .addComponent(button_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(passfield_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        panel_bgLayout.setVerticalGroup(
            panel_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_bgLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(panel_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_uname, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfield_uname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passfield_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_cancel)
                    .addComponent(button_login))
                .addGap(30, 30, 30)
                .addGroup(panel_bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_acc)
                    .addComponent(label_login))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        label_close.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_close.setForeground(new java.awt.Color(250, 250, 250));
        label_close.setText("x");
        label_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_closeMouseClicked(evt);
            }
        });

        label_minimize.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        label_minimize.setForeground(new java.awt.Color(250, 250, 250));
        label_minimize.setText("-");
        label_minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_minimizeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_borderLayout = new javax.swing.GroupLayout(panel_border);
        panel_border.setLayout(panel_borderLayout);
        panel_borderLayout.setHorizontalGroup(
            panel_borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_borderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_loginrheader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label_minimize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_close)
                .addContainerGap())
            .addComponent(panel_bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_borderLayout.setVerticalGroup(
            panel_borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_borderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_borderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_loginrheader)
                    .addComponent(label_close)
                    .addComponent(label_minimize))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_border, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_border, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_cancelMouseClicked

        System.exit(0);
        
    }//GEN-LAST:event_button_cancelMouseClicked

    private void button_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cancelActionPerformed

    }//GEN-LAST:event_button_cancelActionPerformed

    private void label_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_loginMouseClicked

        RegisterForm rf = new RegisterForm();
        rf.setVisible(true);
        rf.pack();
        rf.setLocationRelativeTo(null);
        rf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        
    }//GEN-LAST:event_label_loginMouseClicked

    private void button_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_loginMouseClicked

    }//GEN-LAST:event_button_loginMouseClicked

    private void button_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_loginActionPerformed

        textfield_uname.setBackground(new java.awt.Color(250,250,250));
        passfield_pass.setBackground(new java.awt.Color(250,250,250));

        if(textfield_uname.getText().equals("")){
            textfield_uname.setBackground(new java.awt.Color(255,204,204));
            textfield_uname.setForeground(new java.awt.Color(0, 0, 0));
        }
        if(String.valueOf(passfield_pass.getPassword()).equals("")){
            passfield_pass.setBackground(new java.awt.Color(255,204,204));
            passfield_pass.setForeground(new java.awt.Color(0, 0, 0));
        }
        else{
            Connection con = MyConnection.getConnection();
            PreparedStatement ps;
            
            try {
                ps = con.prepareStatement("SELECT * FROM application WHERE username = ? AND password = ?");
                ps.setString(1, textfield_uname.getText());
                ps.setString(2, String.valueOf(passfield_pass.getPassword()));
                
                ResultSet rs = ps.executeQuery();
                
                if (rs.next())
                {
                    MainForm mf = new MainForm();
                    mf.setVisible(true);
                    mf.pack();
                    mf.setLocationRelativeTo(null);
                    mf.setExtendedState(JFrame.MAXIMIZED_BOTH);
                    MainForm.label_msg.setText("Hi " + textfield_uname.getText() + "! Please fill out all the required information below for us to completely process your application");
                    MainForm.label_msg1.setText(textfield_uname.getText());
                    
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Oops. The email or password is incorrect.");
                }
            } catch (SQLException ex) {
                Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_button_loginActionPerformed

    private void textfield_unameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_unameActionPerformed

    }//GEN-LAST:event_textfield_unameActionPerformed

    private void label_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_closeMouseClicked

        System.exit(0);

    }//GEN-LAST:event_label_closeMouseClicked

    private void label_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_minimizeMouseClicked

        this.setState(JFrame.ICONIFIED);

    }//GEN-LAST:event_label_minimizeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_cancel;
    private javax.swing.JButton button_login;
    private javax.swing.JLabel label_acc;
    private javax.swing.JLabel label_close;
    private javax.swing.JLabel label_login;
    private javax.swing.JLabel label_loginrheader;
    private javax.swing.JLabel label_minimize;
    private javax.swing.JLabel label_pass;
    private javax.swing.JLabel label_uname;
    private javax.swing.JPanel panel_bg;
    private javax.swing.JPanel panel_border;
    private javax.swing.JPasswordField passfield_pass;
    private javax.swing.JTextField textfield_uname;
    // End of variables declaration//GEN-END:variables

    public boolean verifyFields(){
        textfield_uname.setBackground(new java.awt.Color(250,250,250));
        passfield_pass.setBackground(new java.awt.Color(250,250,250));

        if(textfield_uname.getText().equals(""))
        {
            textfield_uname.setBackground(new java.awt.Color(255,204,204));
            textfield_uname.setForeground(new java.awt.Color(0, 0, 0));
        }if(String.valueOf(passfield_pass.getPassword()).equals(""))
        {
            passfield_pass.setBackground(new java.awt.Color(255,204,204));
            passfield_pass.setForeground(new java.awt.Color(0, 0, 0));
        }
        else{
            return true;
        }
        return false;
    }

}
