
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author zoop
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button_add = new javax.swing.JButton();
        label_msg2 = new javax.swing.JLabel();
        jPanel_whitebg = new javax.swing.JPanel();
        jPanel_goldbg = new javax.swing.JPanel();
        jPanel_bluebg = new javax.swing.JPanel();
        jLabel_mfheader = new javax.swing.JLabel();
        button_logout = new javax.swing.JButton();
        label_msg = new javax.swing.JLabel();
        jPanel_bluebg2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        editapplicant = new javax.swing.JButton();
        jPanel_bluebg6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        editfambg = new javax.swing.JButton();
        jPanel_bluebg9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        editessay = new javax.swing.JButton();
        label_msg1 = new javax.swing.JLabel();
        button_submit = new javax.swing.JButton();
        label_msg3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        button_add.setBackground(new java.awt.Color(161, 145, 88));
        button_add.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        button_add.setForeground(new java.awt.Color(250, 250, 250));
        button_add.setText("Add");
        button_add.setToolTipText("");
        button_add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_addMouseClicked(evt);
            }
        });
        button_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_addActionPerformed(evt);
            }
        });

        label_msg2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        label_msg2.setText("Hi <username>! Please fill out all the required information below for us to completely process your application.");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_whitebg.setBackground(new java.awt.Color(250, 250, 250));

        jPanel_goldbg.setBackground(new java.awt.Color(161, 145, 88));

        jPanel_bluebg.setBackground(new java.awt.Color(40, 57, 113));

        jLabel_mfheader.setFont(new java.awt.Font("Century Gothic", 1, 25)); // NOI18N
        jLabel_mfheader.setForeground(new java.awt.Color(250, 250, 250));
        jLabel_mfheader.setText("University Scholarship Application eForm");

        button_logout.setBackground(new java.awt.Color(161, 145, 88));
        button_logout.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        button_logout.setForeground(new java.awt.Color(250, 250, 250));
        button_logout.setText("Log Out");
        button_logout.setToolTipText("");
        button_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_logoutMouseClicked(evt);
            }
        });
        button_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_bluebgLayout = new javax.swing.GroupLayout(jPanel_bluebg);
        jPanel_bluebg.setLayout(jPanel_bluebgLayout);
        jPanel_bluebgLayout.setHorizontalGroup(
            jPanel_bluebgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_bluebgLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel_mfheader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_logout)
                .addGap(34, 34, 34))
        );
        jPanel_bluebgLayout.setVerticalGroup(
            jPanel_bluebgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_bluebgLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanel_bluebgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_mfheader, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_logout))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel_goldbgLayout = new javax.swing.GroupLayout(jPanel_goldbg);
        jPanel_goldbg.setLayout(jPanel_goldbgLayout);
        jPanel_goldbgLayout.setHorizontalGroup(
            jPanel_goldbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_bluebg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_goldbgLayout.setVerticalGroup(
            jPanel_goldbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_goldbgLayout.createSequentialGroup()
                .addComponent(jPanel_bluebg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        label_msg.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        label_msg.setText("Hi <username>! Please fill out all the required information below for us to completely process your application.");

        jPanel_bluebg2.setBackground(new java.awt.Color(250, 250, 250));
        jPanel_bluebg2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel_bluebg2.setForeground(new java.awt.Color(40, 57, 113));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jLabel1.setText("Applicant Profile");

        editapplicant.setText("edit");
        editapplicant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editapplicantMouseClicked(evt);
            }
        });
        editapplicant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editapplicantActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_bluebg2Layout = new javax.swing.GroupLayout(jPanel_bluebg2);
        jPanel_bluebg2.setLayout(jPanel_bluebg2Layout);
        jPanel_bluebg2Layout.setHorizontalGroup(
            jPanel_bluebg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_bluebg2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editapplicant)
                .addContainerGap())
        );
        jPanel_bluebg2Layout.setVerticalGroup(
            jPanel_bluebg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_bluebg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(editapplicant))
        );

        jPanel_bluebg6.setBackground(new java.awt.Color(250, 250, 250));
        jPanel_bluebg6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel_bluebg6.setForeground(new java.awt.Color(40, 57, 113));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jLabel5.setText("Family Background");

        editfambg.setText("edit");
        editfambg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editfambgMouseClicked(evt);
            }
        });
        editfambg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editfambgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_bluebg6Layout = new javax.swing.GroupLayout(jPanel_bluebg6);
        jPanel_bluebg6.setLayout(jPanel_bluebg6Layout);
        jPanel_bluebg6Layout.setHorizontalGroup(
            jPanel_bluebg6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_bluebg6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editfambg)
                .addContainerGap())
        );
        jPanel_bluebg6Layout.setVerticalGroup(
            jPanel_bluebg6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_bluebg6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(editfambg))
        );

        jPanel_bluebg9.setBackground(new java.awt.Color(250, 250, 250));
        jPanel_bluebg9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel_bluebg9.setForeground(new java.awt.Color(40, 57, 113));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 15)); // NOI18N
        jLabel8.setText("Essay");

        editessay.setText("edit");
        editessay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editessayMouseClicked(evt);
            }
        });
        editessay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editessayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_bluebg9Layout = new javax.swing.GroupLayout(jPanel_bluebg9);
        jPanel_bluebg9.setLayout(jPanel_bluebg9Layout);
        jPanel_bluebg9Layout.setHorizontalGroup(
            jPanel_bluebg9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_bluebg9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editessay)
                .addContainerGap())
        );
        jPanel_bluebg9Layout.setVerticalGroup(
            jPanel_bluebg9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_bluebg9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(editessay))
        );

        label_msg1.setBackground(new java.awt.Color(250, 250, 250));
        label_msg1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        label_msg1.setForeground(new java.awt.Color(250, 250, 250));
        label_msg1.setText("<username>");

        button_submit.setBackground(new java.awt.Color(161, 145, 88));
        button_submit.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        button_submit.setForeground(new java.awt.Color(250, 250, 250));
        button_submit.setText("Submit Application");
        button_submit.setToolTipText("");
        button_submit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_submitMouseClicked(evt);
            }
        });
        button_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_submitActionPerformed(evt);
            }
        });

        label_msg3.setBackground(new java.awt.Color(250, 250, 250));
        label_msg3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label_msg3.setForeground(new java.awt.Color(150, 150, 150));
        label_msg3.setText("Note: For fields that are not applicable, fill in with zero or letter O");

        javax.swing.GroupLayout jPanel_whitebgLayout = new javax.swing.GroupLayout(jPanel_whitebg);
        jPanel_whitebg.setLayout(jPanel_whitebgLayout);
        jPanel_whitebgLayout.setHorizontalGroup(
            jPanel_whitebgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_goldbg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_whitebgLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(jPanel_whitebgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label_msg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_bluebg2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_bluebg6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_bluebg9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_msg1)
                    .addComponent(label_msg3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(jPanel_whitebgLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_submit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_whitebgLayout.setVerticalGroup(
            jPanel_whitebgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_whitebgLayout.createSequentialGroup()
                .addComponent(jPanel_goldbg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(label_msg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_msg1)
                .addGap(10, 10, 10)
                .addComponent(label_msg3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_bluebg2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_bluebg6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_bluebg9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(button_submit)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_whitebg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_whitebg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editapplicantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editapplicantMouseClicked

    }//GEN-LAST:event_editapplicantMouseClicked

    private void editapplicantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editapplicantActionPerformed

        ApplicantForm af = new ApplicantForm();
        af.setVisible(true);
        af.pack();
        af.setLocationRelativeTo(null);
        ApplicantForm.label_uname.setText(label_msg1.getText());
        
    }//GEN-LAST:event_editapplicantActionPerformed

    private void editfambgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editfambgMouseClicked

    }//GEN-LAST:event_editfambgMouseClicked

    private void editfambgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editfambgActionPerformed

        FamilyForm ff = new FamilyForm();
        ff.setVisible(true);
        ff.pack();
        ff.setLocationRelativeTo(null);
        FamilyForm.label_uname.setText(label_msg1.getText());
        
    }//GEN-LAST:event_editfambgActionPerformed

    private void editessayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editessayMouseClicked

        EssayForm esf = new EssayForm();
        esf.setVisible(true);
        esf.pack();
        esf.setLocationRelativeTo(null);
        EssayForm.label_uname1.setText(label_msg1.getText());
        
    }//GEN-LAST:event_editessayMouseClicked

    private void button_addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_addMouseClicked

        System.exit(0);
    }//GEN-LAST:event_button_addMouseClicked

    private void button_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_addActionPerformed

        this.dispose();

    }//GEN-LAST:event_button_addActionPerformed

    private void button_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_logoutMouseClicked

        System.exit(0);
    }//GEN-LAST:event_button_logoutMouseClicked

    private void button_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_logoutActionPerformed

        LoginForm lf = new LoginForm();
        lf.setVisible(true);
        lf.pack();
        lf.setLocationRelativeTo(null);
        this.dispose();

    }//GEN-LAST:event_button_logoutActionPerformed

    private void button_submitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_submitMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_button_submitMouseClicked

    private void button_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_submitActionPerformed

        String status = "COMPLETE; application for review";
        
        Connection con = MyConnection.getConnection();
        PreparedStatement ps;
        
            try {
                ps = con.prepareStatement("UPDATE `application` SET `status`= ? WHERE `username`= ?");
                ps.setString(1, status);
                ps.setString(2, label_msg1.getText());

                if(ps.executeUpdate() > 0){
                    JOptionPane.showMessageDialog(null, "Your scholarship application has been submitted for review.\n We will let you know if you qualified.");
                    editapplicant.setVisible(false);
                    editfambg.setVisible(false);
                    editessay.setVisible(false);
                    button_submit.setVisible(false);
                }
            }
            catch (SQLException ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_button_submitActionPerformed

    private void editessayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editessayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editessayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_add;
    private javax.swing.JButton button_logout;
    public static javax.swing.JButton button_submit;
    public static javax.swing.JButton editapplicant;
    public static javax.swing.JButton editessay;
    public static javax.swing.JButton editfambg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_mfheader;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel_bluebg;
    private javax.swing.JPanel jPanel_bluebg2;
    private javax.swing.JPanel jPanel_bluebg6;
    private javax.swing.JPanel jPanel_bluebg9;
    private javax.swing.JPanel jPanel_goldbg;
    private javax.swing.JPanel jPanel_whitebg;
    public static javax.swing.JLabel label_msg;
    public static javax.swing.JLabel label_msg1;
    public static javax.swing.JLabel label_msg2;
    public static javax.swing.JLabel label_msg3;
    // End of variables declaration//GEN-END:variables
}
